articles/urls.py
from django.urls import path

from .views import article_search_view, article_create_view, article_detail_view


app_name = 'articles'
urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'),
    path('<slug:slug>/', article_detail_view, name='detail'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import home_view
from accounts.views import login_view, logout_view, register_view
from search.views import search_view


urlpatterns = [
    path('', home_view),
    path('cooking/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls')),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
     <script src="https://unpkg.com/htmx.org@1.7.0"></script>
    <link rel="stylesheet" href="{% static 'recipes/recipes-htmx.css' %}"/>

</head>
<body>
     <h1>Hello World</h1>

     {% include 'search/search-form.html' %}

<!--     <form action="/articles/" method="GET">-->
<!--         <input type="text" name="q" />-->
<!--         <input type="submit"  />-->
<!--     </form>-->

    {% block content %}
    {% endblock content %}

    <script>
        document.body.addEventListener("htmx:configRequest", (event)=>{
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'
        })
    </script>


</body>
</html>

templates/home.html
{% extends "base.html" %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>



<body>
    {% block content %}

     <div style="margin-top:30px;">
         <form action="{% url 'articles:create' %}">
            <input type="submit" value="Create New Article"/>
        </form>
     </div>

    <h1 style="color:green">{{ object.title }} (id: {{ object.id }})</h1>
    <p style="color:green">{{ object.text }}</p>



    <ul>
        {% for article in object_list %}
            {% if article.title %}
        <li><a href="{{ article.get_absolute_url }}">{{ article.title }} - {{ article.text }}</a></li>
                {% endif %}
        {% endfor %}
    </ul>

    {% endblock content %}
</body>
</html>