blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import home_view
from accounts.views import login_view, logout_view, register_view
from search.views import search_view


urlpatterns = [
    path('', home_view),
    path('cooking/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls')),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

recipes/urls.py
from django.urls import path

from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_delete_view,
    recipe_create_view,
    recipe_update_view,
    # recipe_detail_hx_view,
    recipe_ingredient_update_hx_view,
    recipe_ingredient_delete_view
)

app_name = 'recipes'
urlpatterns = [
    path("", recipe_list_view, name='list'),
    path("create/", recipe_create_view, name='create'),

    path("<int:id>/change/", recipe_update_view, name='update'),
    path("<int:id>/delete/", recipe_delete_view, name='delete'),
    path("<int:id>/", recipe_detail_view, name='detail'),
    path("<int:parent_id>/ingredient/<int:id>/delete/", recipe_ingredient_delete_view, name='ingredient-delete'),

    # path("hx/<int:id>/", recipe_detail_hx_view, name='hx-detail'),
    path("hx/<int:parent_id>/ingredient/<int:id>", recipe_ingredient_update_hx_view, name='hx-ingredient-detail'),
    path("hx/<int:parent_id>/ingredient/", recipe_ingredient_update_hx_view, name='hx-ingredient-create'),

]

recipes/models.py
import pint
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.db.models import Q

from .utils import number_str_to_float
from .validators import validate_unit_of_measure

# Create your models here.


class RecipeQuerySet(models.QuerySet):
    def search(self, query=None):
        if query is None or query == '':
            return self.none()
        lookups = (
                Q(name__icontains=query) |
                Q(description__icontains=query) |
                Q(directions__icontains=query)
        )
        return self.filter(lookups)


class RecipeManager(models.Manager):
    def get_queryset(self):
        return RecipeQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)


class Recipe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    objects = RecipeManager()

    @property
    def title(self):
        return self.name

    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'id': self.id})

    def get_hx_url(self):
        return reverse('recipes:hx-detail', kwargs={'id': self.id})

    def get_update_url(self):
        return reverse('recipes:update', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('recipes:delete', kwargs={'id': self.id})

    def get_ingredients_children(self):
        return self.recipeingredient_set.all()


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    quantity = models.CharField(max_length=15)
    quantity_as_float = models.FloatField(blank=True, null=True)
    unit = models.CharField(max_length=10, validators=[validate_unit_of_measure, ])
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return self.recipe.get_absolute_url()

    def get_delete_url(self):
        kwargs = {
            'parent_id': self.recipe.id,
            'id': self.id
        }
        return reverse('recipes:ingredient-delete', kwargs=kwargs)

    def get_hx_update_url(self):
        kwargs = {
            'parent_id': self.recipe.id,
            'id': self.id
        }
        return reverse('recipes:hx-ingredient-detail', kwargs=kwargs)

    def convert_to_system(self, system='mks'):
        if self.quantity_as_float is None:
            return None
        ureg = pint.UnitRegistry(system=system)
        measurement = self.quantity_as_float * ureg[self.unit]
        return measurement

    def as_mks(self):
        measurement = self.convert_to_system(system='mks')
        return measurement.to_base_units()

    def as_imperial(self):
        measurement = self.convert_to_system(system='imperial')
        return measurement.to_base_units()

    def save(self, *args, **kwargs):
        qty = self.quantity
        qty_as_float, qty_as_float_success = number_str_to_float(qty)
        if qty_as_float_success:
            self.quantity_as_float = qty_as_float
        else:
            self.quantity_as_float = None
        super().save(*args, **kwargs)

recipes/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
# from django.forms.models import modelformset_factory
# Create your views here.
from django.urls import reverse

from .models import Recipe, RecipeIngredient
from .recipes_forms import RecipeForm, RecipeIngredientForm


""" CRUD - Create Retrieve Update Delete """


@login_required
def recipe_list_view(request):
    qs = Recipe.objects.filter(user=request.user)
    context = {
        'object_list': qs
    }
    return render(request, 'recipes/list.html', context)


@login_required
def recipe_detail_view(request, id=None):
    try:
        obj = Recipe.objects.get(id=id, user=request.user)
    except:
        obj = None
    if obj is None:
        if request.htmx:
            return HttpResponse('<h1 style="color:red">Not found</h1>')
        raise Http404
    context = {
        'object': obj
    }
    if request.htmx:

        return render(request, 'recipes/partials/detail.html', context)
    return render(request, 'recipes/detail.html', context)


@login_required
def recipe_delete_view(request, id=None):
    try:
        obj = Recipe.objects.get(id=id, user=request.user)
    except:
        obj = None
    if obj is None:
        if request.htmx:
            return HttpResponse("Not found")
        raise Http404
    if request.method == "POST":
        obj.delete()
        success_url = reverse('recipes:list')
        if request.htmx:
            headers = {
                'HX-Redirect': success_url
            }
            return HttpResponse('Success', headers=headers)
        return redirect(success_url)
    context = {
        'object': obj
    }
    return render(request, 'recipes/delete.html', context)


@login_required
def recipe_ingredient_delete_view(request, parent_id=None, id=None):
    try:
        obj = RecipeIngredient.objects.get(id=id, recipe__id=parent_id, recipe__user=request.user)
    except:
        obj = None
    if obj is None:
        if request.htmx:
            return HttpResponse("Not found")
        raise Http404
    if request.method == "POST":
        obj.delete()
        success_url = reverse('recipes:detail', kwargs={'id': parent_id})
        if request.htmx:
            name = obj.name
            return render(request, 'recipes/partials/ingredient-inline-delete-response.html', {'name': name})

        return redirect(success_url)
    context = {
        'object': obj
    }
    return render(request, 'recipes/delete.html', context)



@login_required
def recipe_create_view(request):
    form = RecipeForm(request.POST or None)
    # create_ingredient_url = reverse('recipes:hx-ingredient-create', kwargs={'parent_id': id})
    context = {
        'form': form,
        # 'create_ingredient_url': create_ingredient_url
    }
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        if request.htmx:
            headers = {
                "HX-Redirect": obj.get_absolute_url()
            }
            return HttpResponse("Created", headers=headers)
        return redirect(obj.get_absolute_url())
    return render(request, 'recipes/create-update.html', context)


@login_required
def recipe_update_view(request, id=None):
    obj = get_object_or_404(Recipe, id=id, user=request.user)
    form = RecipeForm(request.POST or None, instance=obj)
    create_ingredient_url = reverse('recipes:hx-ingredient-create', kwargs={'parent_id': id})
    context = {
        'form': form,
        'object': obj,
        'create_ingredient_url': create_ingredient_url
    }

    if form.is_valid():
        form.save()
        context['message'] = 'the recipe was saved'

    if request.htmx:
        return render(request, 'recipes/partials/forms.html', context)

    return render(request, 'recipes/create-update.html', context)



@login_required
def recipe_ingredient_update_hx_view(request, parent_id=None, id=None):
    if not request.htmx:
        raise Http404
    try:
        parent_obj = Recipe.objects.get(id=parent_id, user=request.user)
    except:
        parent_obj = None
    if parent_obj is None:
        return HttpResponse('<h1 style="color:red">Not found</h1>')

    instance = None
    if id is not None:
        try:
            instance = RecipeIngredient.objects.get(recipe=parent_obj, id=id)
        except:
            instance = None
    form = RecipeIngredientForm(request.POST or None, instance=instance)
    url = instance.get_hx_update_url if instance else reverse('recipes:hx-ingredient-create', kwargs={'parent_id': parent_id})
    context = {
        'object': instance,
        'form': form,
        'url': url
    }
    if form.is_valid():
        new_obj = form.save(commit=False)
        if instance is None:
            new_obj.recipe = parent_obj
        new_obj.save()
        context['object'] = new_obj
        return render(request, 'recipes/partials/ingredient-inline.html', context)

    return render(request, 'recipes/partials/ingredient-form.html', context)





""" This is an old view with formset and without HTMX"""

# @login_required
# def recipe_update_view(request, id=None):
#     obj = get_object_or_404(Recipe, id=id, user=request.user)
#     form = RecipeForm(request.POST or None, instance=obj)
#     RecipeIngredientFormset = modelformset_factory(RecipeIngredient, form=RecipeIngredientForm, extra=0)
#     formset = RecipeIngredientFormset(request.POST or None, queryset=obj.get_ingredients_children())
#     context = {
#         'form': form,
#         'formset': formset,
#         'object': obj
#     }
#
#     if all([form.is_valid(), formset.is_valid()]):
#         parent = form.save(commit=False)
#         parent.save()
#         for form in formset:
#             child = form.save(commit=False)
#             child.recipe = parent
#             child.save()
#         context['message'] = 'the recipe was saved'
#
#     if request.htmx:
#         return render(request, 'recipes/partials/forms.html', context)
#
#     return render(request, 'recipes/create-update.html', context)

templates/recipes/create-update.html
{% extends "base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block content %}

    <style>
        .ingredient-form {
            border-bottom: 1px solid black;
            }
        .hidden {
            display: none
            }
    </style>

<!--    {% if message %}-->

<!--        <p>{{ message }}</p>-->

<!--    {% endif %}-->

    <div style="margin-top:30px;">
        {% include 'recipes/partials/forms.html' %}

        <h3>Ingredients</h3>
        {% for ingredient in object.get_ingredients_children %}
            {% include 'recipes/partials/ingredient-inline.html' with object=ingredient %}
        {% endfor %}
        {% if create_ingredient_url %}
            <div id="ingredient-create">

            </div>

            <button hx-get="{{ create_ingredient_url }}" hx-trigger="click"
                        hx-target="#ingredient-create" hx-swap="beforeend">Add new ingredient</button>
        {% endif %}
    </div>


    <script>

        // const addMoreBtn = document.getElementById("add-more")


        document.addEventListener("click", (event)=>{
            if (event.target.id == "add-more") {
                add_new_form(event)
            }
            console.log(event.target, event.id)
        })
        // addMoreBtn.addEventListener("click", add_new_form)

        function add_new_form(event) {
            if (event) {
                event.preventDefault()
            }

            // now add new empty form

            const totalNewForms = document.getElementById("id_form-TOTAL_FORMS")
            const currentIngredientForms = document.getElementsByClassName("ingredient-form")
            let currentFormCount = currentIngredientForms.length

            const formCopyTarget = document.getElementById("ingredient-form-list")

            const copyEmptyFormEl = document.getElementById("empty-form").cloneNode(true)
            copyEmptyFormEl.setAttribute('class', 'ingredient-form')
            copyEmptyFormEl.setAttribute('id', `form-${currentFormCount}`)
            const regex = new RegExp('__prefix__', 'g')
            copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currentFormCount)
            totalNewForms.setAttribute('value', currentFormCount + 1)
            formCopyTarget.append(copyEmptyFormEl)
        }
    </script>


    {% endblock content %}
</body>
</html>

templates/recipes/delete.html
{% extends "base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block content %}

        {% if object %}
        <form method="POST" action=".">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object.name|title }}"?</p>

            <button type="submit">Yes, delete.</button>
        {% endif %}
        </form>

    {% endblock content %}
</body>
</html>

templates/recipes/detail.html
{% extends "base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block content %}

    <div hx-get="{{ hx_url }}" hx-trigger="revealed">
        <div class="htmx-indicator" style="margin-top:30px;">Loading...</div>
    </div>

<!--    <h1>{{ object.name }} {% if object.get_update_url %}<small><a href='{{ object.get_update_url }}'>Edit</a></small>{% endif %}</h1>-->
<!--    <p>{{ object.description }}</p>-->
<!--    <p>{{ object.directions }}</p>-->

<!--    {% for ingredient in object.get_ingredients_children %}-->

<!--        <h2>{{ ingredient.name }}</h2>-->
<!--        <p>{{ ingredient.as_imperial }}</p>-->
<!--        <p>{{ ingredient.as_mks }}</p>-->

<!--    {% endfor %}-->

    {% endblock content %}
</body>
</html>

templates/recipes/list.html
{% extends "base.html" %}



{% block content %}

    <div style="margin-top:30px;">
         <form action="{% url 'recipes:create' %}">
            <input type="submit" value="Add Recipe"/>
        </form>
     </div>

    <h1 style="color:green">My recipes</h1>



    <ul>
        {% for recipe in object_list %}
            <li><a href="{{ recipe.get_absolute_url }}">{{ recipe.name }}</a></li>
        {% endfor %}
    </ul>


{% endblock content %}

templates/recipes/upload-image.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>